### ISSUE TITLE
RF-Solver-Edit 

### ISSUE THREAD

**Issue by C00reNUT** [pureexe/rf-inversion-sd3#2]
Do you think could work with SD3? https://github.com/wangjiangshan0725/RF-Solver-Edit

**Comment by pureexe** [comment]
Should be work with with SD3. I tried to implement but result is not as good as their flux implemnetation. I'm currently looking into it root cause. If i can make it become better result. i will shared the code.

**Comment by C00reNUT** [comment]
Thank you!
