### ISSUE TITLE
About null prompt inversion

### ISSUE THREAD

**Issue by lzq0529** [pureexe/rf-inversion-sd3#3]
In the absence of text input, the resulting picture is quite different from the original image. I would like to ask you about the relevant parameter Settings for null prompt inversion implementation, or the relevant code.

**Comment by pureexe** [comment]
If you want to have inversion to produce the same image. 
You can either increasing `--num_steps` assume the text prompt on inversion and generation is the same ("" null or empty string as you mention)

 or increasing `--end_step`  to let's the RF-Inversion guide the output result.
